<?php echo $this->form()->openTag($this->form); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Simulador de Pago Tarjeta VISA</h4>
    </div>
    <div class="panel-body">
        
        <div class="form-group">
            <label for="subtitulo" class="col-lg-2 control-label">Transacción :</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($this->form->get('transaccion')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="subtitulo" class="col-lg-2 control-label">Monto :</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($this->form->get('monto')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="subtitulo" class="col-lg-2 control-label">Tarjeta :</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($this->form->get('tarjeta')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="subtitulo" class="col-lg-2 control-label">Estado :</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($this->form->get('estado')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-7">
                <?php echo $this->formRow($this->form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
